server:
  port: 8080

spring:
  application:
    name: smartops-data-processor

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.smartops: INFO
